url: https://www.m.toogoodbruh.com   # with the https protocol
enforce_ssl: www.m.toogoodbruh.com   # without any protocol

# For example, my configuration is this:
url: https://m.toogoodbruh.com
enforce_ssl: m.toogoodbruh.com
